digital-land/submit

- src/routes/form-wizard/steps.js
- src/views/confirmation.html
- test/acceptance/upload_data.test.js
Ticket: https://trello.com/c/6XKMHVYh/1098-add-confirmation-page
This ticket adds the confirmation page at the end of the form
> Confirmation page

- src/assets/scss/index.scss
- src/controllers/errorsController.js
- src/views/errors.html
- test/testData/API_RUN_PIPELINE_RESPONSE.json
- test/unit/errorsController.test.js
- test/unit/errorsPage.test.js
Ticket: https://trello.com/c/dYjAIi79/1120-mvp-make-the-issues-meaningful-on-the-error-page
this PR shows error descriptions instead of
> Show error descriptions instead of types

- src/controllers/errorsController.js
- src/views/errors.html
- test/unit/errorsController.test.js
- test/unit/errorsPage.test.js
Ticket: https://trello.com/c/q9vRc045/1155-errors-need-grouping-by-error-and-not-just-column
this ticket ensure the errors in the error summary are grouped not only by field but also by issue-type
> Group error messages

- index.js
- src/controllers/pageController.js
- src/controllers/uploadController.js
- src/utils/hasher.js
- test/mock-api/index.js
- test/unit/PageController.test.js
- test/unit/hasher.test.js
Ticket: https://trello.com/c/RxFpdnnx/1138-record-and-display-metrics-via-logs
This PR makes sure to log not the raw IP and session id, but instead a hash of these values
additional changes: 
- updated the mock api to remove the missing-fields field and instead return the column-field-log field
> hash the IP address and session id

- src/views/confirmation.html
- src/views/layouts/main.html
- src/views/start.html
Ticket: https://trello.com/c/Smc4uN5i/1188-quick-changes-before-production
this ticket fixes the following
- remove content to the right on start page (related content and explore this topic)
- final green box should contain ‘send us your data’
- remove privacy notice link from footer
- [link ](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)to open gov license needs adding to confirm page
- feedback link on confirmation page not working
> Quick fixes before prod

- src/controllers/errorsController.js
- src/views/errors.html
- test/acceptance/missing_required_column.test.js
- test/testData/API_RUN_PIPELINE_RESPONSE.json
- test/unit/errorsController.test.js
- test/unit/errorsPage.test.js
Ticket: https://trello.com/c/5Lx4U7uL/1189-improve-error-summary-messages
This PR changes the error summary to render messages received from the backend
> now render error summary from api

- src/controllers/datasetController.js
- src/controllers/uploadController.js
- src/routes/form-wizard/steps.js
- src/utils/utils.js
Tickets:
- https://trello.com/c/qrnJEM9C/1169-users-can-check-listed-building-outlines-data-on-publish
- https://trello.com/c/YQXWuBFa/1199-users-can-check-tree-preservation-zone-data-on-publish
- https://trello.com/c/4mQjyEj1/1222-make-the-organisation-a-non-mandatory
This PR primarily adds two datasets, tree-preservation-zone and listed-building-outlines as options for validation
in addition it
- stops sending an organisation (as this is no longer mandatory)
- ensures we are sending the correct data-subject with the dataset
> New datasets

- dockerfile
a new version of npm has been launched, but is incompatible with out codebase. this ensures only the compatible version of npm is used
> Downgrade node

- index.js
- src/controllers/errorsController.js
- src/filters/filters.js
- src/filters/prettifyColumnName.js
- src/views/errors.html
- test/testData/API_RUN_PIPELINE_RESPONSE.json
- test/unit/errorsPage.test.js
- test/unit/prettifyColumnName.test.js
Ticket: https://trello.com/c/RNhBP4Lx/1178-introduce-a-new-column-in-issue-log-to-handle-customized-messages?filter=member:georgegoodall8
this ticket adds a filter for formatting column names displayed in error messages in a prettier way
some examples
document-url  -> Document URL
start-date        -> Start date
geography      -> Geography
> Pretty column name lookup

- index.js
- src/controllers/uploadController.js
- src/controllers/uploadFileController.js
- src/controllers/uploadUrlController.js
- src/utils/logging.js
- test/unit/PageController.test.js
- test/unit/uploadFileController.test.js
this ticket removes the recording of IP address' from the logs
> remove ip address from logs

- src/utils/utils.js
Ticket: https://trello.com/c/mdEmQR4H/3289-enable-check-application-to-review-lpa-api-links
this ticket is to add another accepted mimetype to the geojson format
> add geojson mime type

- src/controllers/CheckAnswersController.js
- test/unit/check-answers.test.js
- test/unit/checkAnswersController.test.js
Currently email notification failures are not handled properly. We want the errors handled and logged. 
[Trello](https://trello.com/c/d36ZqNM4)
> form submission: error handling and logging for email notifications

- config/default.yaml
- src/routes/health.js
- src/serverSetup/middlewares.js
- src/serverSetup/session.js
- src/utils/fetchLocalAuthorities.js
- test/unit/health.test.js
Various unrelated changes: 
- change default PORT to 8011 (5000 conflicts with a macOS service)
- better logging on Redis connection error
- remove unnecessary async/await
- less noisy test output (omit logging stack traces in few places in 'test' environment)
> NOTICKET: minor tweaks

- config/index.js
- config/production.yaml
- config/test.yaml
- package.json
- src/serverSetup/nunjucks.js
- src/views/common/smartlook.js
- src/views/layouts/main.html
Adds integration with Smartlook to enable recording (anonymised) website usage data.
This is a barebones integration - no custom events at the moment. It will be included in the served HTML only when the server has appropriate environment variables set (see config/production.yaml).
> Add Smartlook integration

- .gitignore
- config/index.js
- src/assets/js/statusPage.js
- src/controllers/submitUrlController.js
- src/controllers/uploadFileController.js
- src/filters/validationMessageLookup.js
- src/models/requestData.js
- src/models/responseDetails.js
- src/routes/health.js
- src/utils/fetchLocalAuthorities.js
- src/utils/logger.js
- test/unit/requestData.test.js
- test/unit/responseDetails.test.js
- test/unit/validationLookup.test.js
Separate loggers for "test" and other envs, to silence logging during
the test runs. Also, replace any instances of `console.*` calls.
> Logging improvements

- .github/workflows/featureDeploy.yml
- src/assets/js/list-filter.js
- src/controllers/OrganisationsController.js
- src/views/organisations/find.html
- test/unit/organisationsController.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/9?pane=issue&itemId=71553596
before reviewing this ticket, please review this ticket https://github.com/digital-land/lpa-data-validator-frontend/pull/201
This ticket updates the controller so it receives the list of organisations from datasette
> Feat/org finder/datasette query

- src/controllers/OrganisationsController.js
- src/services/performanceDbApi.js
- test/unit/performanceDbApi.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/15?filterQuery=-status%3ABacklog%2CReady%2CDone%2CUnprioritised&pane=issue&itemId=74598465
this ticket updates the datasette query to ensure that only the 8 datasets the check tool is currently checking are shown in the dashboard
> only show 8 datasets on dashboard

- src/services/performanceDbApi.js
Empty datasets are a valid return value from `getLpaOverview()` query. This if following other changes that removed access of potentially `null` properties. 
Related [issue](https://github.com/digital-land/lpa-data-validator-frontend/issues/271#issue-2463309711)
> Allow empty datasets in performanceDbApi.getLpaOverview()

- package-lock.json
Fix vulnerabilities in npm packages
Before this fix, there were:
12 vulnerabilities (2 moderate, 10 high)
After this fix, there are now 0 vulnerabilities.
To reproduce the issue - please run `npm audit`
> Fix vulnerabilities in npm packages

- src/views/layouts/main.html
Remove `...` from the body
This was added in unintentionally.
> Remove `...` from the body

- src/controllers/OrganisationsController.js
- src/routes/schemas.js
- src/views/organisations/datasetTaskList.html
- test/unit/datasetTaskListPage.test.js
Previously params were hardcoded therefore they always went to the same location.
This change fixes it so that it dynamically changes based on the page context.
- Ticket Link - https://github.com/digital-land/submit/issues/321
- Closes #321
1. Go to https://check.planning.data.gov.uk/organisations/local-authority:BNE/article-4-direction
1. Click on `View the dataset on the Planning Data platform` link
> Fix URL to have the correct params

- src/views/organisations/http-error.html
- test/unit/http-errorPage.test.js
The http-error.html template contains a re-submit link that points to the submit service. We should change it to point to the 'get started' page.
Closes #351 
https://github.com/digital-land/submit/issues/346
> point re-submit link on error page to 'get-started' page

- src/controllers/submitUrlController.js
- test/unit/submitUrlController.test.js
Fixes #183 
The web server did not like the (default) 'User-Agent' header we passed and trying to access the URL resulted in 403 error. 
This PR passes a 'check service' string as 'User-Agent'. 
Also: 
- renamed the awkwardly named fn to `headRequets`
- run some of the URL validators _before_ firing the HEAD request
> Pass User-Agent header in URL validation HEAD request

- config/default.yaml
- config/index.js
- config/util.js
- src/controllers/submitUrlController.js
This moves the recently introduced User-Agent header we pass in requests (to verify accessibility of a user supplied URL) to the config file and replaces "check service" value with "GOVUK Planning Data: Check Service" (suggested by @DilwoarH )
No ticket. Builds on #344 
> make check service User-Agent header value configurable

- package-lock.json
- package.json
- Bug Fix
This ticket changes the dependency source for [govuk_prototype_filters](https://github.com/x-govuk/govuk-prototype-filters) to use [our fork](https://github.com/GeorgeGoodall/govuk-prototype-filters/tree/fix/markdownFilterStackOverflow) which has had two changes compared to the upstream repo: 
- A fix for the stack overflow issue in the govuk_markdown filter
- downgraded version of marked tp v13 as marked v14 seems to break stuff
the reason we are using a fork and not just contributing to the upstream repo is because it has failing tests from a recent commit. We have opened a [PR](https://github.com/x-govuk/govuk-prototype-filters/pull/81), but can't get it approved due to failing tests anyway
- Related Issue: #313 
No, and this is why: _only a dependency change_
> downgrade govuk filters markdown dependency and modify filter code

- src/views/organisations/issueDetails.html
- test/unit/issueDetailsPage.test.js
Fixes a bug where map would still show if no geometries are passed in. This causes a JS exception and the map to show unintentionally.
- Closes #414 
> Hide map when no geometries are passed in

- src/models/requestData.js
- src/models/responseDetails.js
- src/services/asyncRequestApi.js
- src/views/check/results/no-errors.html
- test/unit/responseDetails.test.js
`ResponseDetails.getGeometries()` returns array of `"POINT (X Y)"` when geometry data is stored in a pair of columns: `GeoX` and `GeoY`.
There async-request-api made changes recently that can potentially help us with the above (see https://github.com/digital-land/async-request-backend/pull/41), but not in this particular PR.
We don't make use of the new 'transformed_row' entry in the body of '/requests/:result-id/response-details' response (of async api), because that entry is present only when 'dataset=brownfield-land' is passed as param. We currently don't support 'brownfield-land' datasets, so that's not available in to us.
Instead, 'POINT' value is extracted manually from the GeoX, GeoY columns (when present).
- Closes #310
> handle GeoX, GeoY columns in input data.

- src/controllers/OrganisationsController.js
- test/unit/organisationsController.test.js
Replaces wrong identifier (`resourceId`) with the correct one.
Quick fix, no ticket.
Discovered by @alextea 
> Is it a bug that this page is not showing all the fields? https://submit.planning.data.gov.uk/organisations/local-authority:NSM/article-4-direction/missing%20value/document-url/1
Compare left (bug present) and right (bug fixed) below:
> NOTICKET: fix wrong referenece to resource id

- src/views/organisations/overview.html
- test/unit/lpaOverviewPage.test.js
For datasets that "Need fixing" we should display short text summarizing the issue (atm, it's the number of issues). Incorrect condition in the template cause the default 'Data URL submitted' text to be displayed instead.
No ticket.
This is how it looks in PROD at the moment:
> fix issue count

- package-lock.json
- package.json
- src/middleware/datasetOverview.middleware.js
This should only be deployed at the same time as [this](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html)
- Refactor
The specification has been updated to store specs as json strings (instead of invalid json strings that use single quotes)
This PR updates the code responsible for parsing this
- Related PR: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html
- Closes #491 
- No
> change to just use inbuilt json and remove JSON 5

- src/controllers/submitUrlController.js
- src/filters/filters.js
- src/middleware/issueDetails.middleware.js
- src/middleware/middleware.builders.js
- src/middleware/overview.middleware.js
- src/routes/schemas.js
- src/services/performanceDbApi.js
- src/views/organisations/overview.html
- test/unit/lpaOverviewPage.test.js
- test/unit/middleware/issueDetails.middleware.test.js
- test/unit/middleware/overview.middleware.test.js
- test/unit/performanceDbApi.test.js
We want to change how we calculate the number of issues on the organisation overview page. Specifically we want
-  an issue affecting all rows in a column to be counted as one issue
- a column issue which affects _n_ fileds should be counted as _n_ issues.
Closes #439 
Examples differences between `main` and this branch.
- prod:  https://submit.planning.data.gov.uk/organisations/local-authority:NLN
- this pr: https://submit-pr-475.herokuapp.com/organisations/local-authority:NLN
- prod: https://submit.planning.data.gov.uk/organisations/local-authority:LBH
- this pr: https://submit-pr-475.herokuapp.com/organisations/local-authority:LBH
> Issue count change

- src/middleware/datasetOverview.middleware.js
- src/middleware/datasetTaskList.middleware.js
- src/middleware/issueDetails.middleware.js
- src/middleware/overview.middleware.js
Fixes an issue where missing org could down the server if it's run in parallel.
The `fallbackPolicy` doesn't end the request therefore leaves the thread open. This causes the server to crash the next time the user refreshes as a new header is being attached after the request was already sent.
This is initial analysis and needs further investigation.
Ref: https://github.com/digital-land/submit/blob/main/src/middleware/middleware.builders.js#L43
This line sends a 404 res return but doesn't close the request.
- Ticket Link
- Closes #
_We encourage you to keep the code coverage percentage at 80% …
> Hotfix: Fixes an issue where missing org could down the server if it's run in parallel

- config/default.yaml
- src/assets/js/map.js
- src/middleware/datasetOverview.middleware.js
- src/middleware/datasetTaskList.middleware.js
- src/middleware/issueDetails.middleware.js
- src/utils/utils.js
- src/views/organisations/dataset-overview.html
- Feature
Adds the brownfield land dataset to the submit service as options for the dashboard and check tool
- Closes #531 
> 531 display brownfield land datasets as an option on the lpa dashboard page

- src/middleware/common.middleware.js
- src/middleware/entryIssueDetails.middleware.js
- src/routes/schemas.js
- test/unit/middleware/common.middleware.test.js
- test/unit/middleware/entityIssueDetails.middleware.test.js
- test/unit/middleware/entryIssueDetails.middleware.test.js
Fixes issues with incorrect handling of `dataRange` object by:
- putting schema checks in the right places
- not relying on the generic 404 middleware
- Closes #764
production: this [link](https://submit.planning.data.gov.uk/organisations/local-authority:BST/brownfield-land/invalid%20organisation/organisation/entry) causes trouble
same in preview instance: [link](https://submit-pr-839.herokuapp.com/organisations/local-authority:BST/brownfield-land/invalid%20organisation/organisation/entry) results in 404
- ~~[ ] Code has been checked and approved~~
- ~~[ ] Design has been checked and approved~~
- ~~[ ] Product and business logic has been checked and proved~~
> fix: invalid data range

- .github/workflows/github-pages.yml
- .gitignore
- jsdoc.json
- package-lock.json
- package.json
- Fixes github actions configuration
- Includes markdown files in our `docs` in the generated docs
- Adds JSDoc plugin to handle import statements in comments, e.g. `@param {import('express').Request} req - request object`
- Related #898
> JSDocs tweaks
