.github/workflows/lint_and_test_on_push.yml, test/helloWorld.test.js
Ticket: https://trello.com/c/UCi1bS41/1065-create-an-initial-repo-for-the-frontend-of-the-data-validation-tool
Added a workflow for running the testing and linting on a pull request
also updated the github settings to require this workflow to pass to allow merge
=> GitHub workflows

package-lock.json, package.json
Just updating the packages ready for the next PR
=> package.json and package lock updates for next PR

changelog.md, src/views/errors.html, src/views/start.html
Ticket: https://trello.com/c/RfemdzpF/1085-update-the-old-pages-to-match-the-latest-version-of-the-prototype
=> updated start and errors pages

config/index.js, index.js, package-lock.json, package.json, playwright.config.js, src/controllers/MyController.js, src/controllers/dataSubjectController.js, src/controllers/datasetController.js, src/controllers/errorsController.js, src/controllers/uploadController.js, src/routes/form-wizard/fields.js, src/routes/form-wizard/index.js, src/routes/form-wizard/steps.js, src/views/errors.html, test/mock-api/index.js, test/unit/errorsController.test.js, test/unit/errorsPage.test.js, test/unit/uploadController.test.js
Ticket: https://trello.com/c/FvaXRlsz/1103-integrate-frontend-with-backend
this PR updates the front end to make it compatible with the backend in preparation for the show and share on Monday
=> DRAFT: Make work with api

src/filters/validationMessageLookup.js, src/routes/form-wizard/fields.js, src/routes/form-wizard/steps.js, src/views/lpa.html, test/acceptance/upload_data.test.js, test/acceptance/validation_errors.test.js
Ticket: https://trello.com/c/J88kSGpl/1096-add-local-planning-authority-form-step-page
This PR adds the lpa collection page
=> Your lpa page

src/controllers/errorsController.js, src/routes/form-wizard/steps.js, src/views/check.html, src/views/errors.html, test/acceptance/upload_data.test.js, test/unit/errorsController.test.js, test/unit/errorsPage.test.js
Ticket: https://trello.com/c/2Fs4r5kK/1097-add-summary-form-step-page
This ticket adds a check page to the end of the form wizard
=> Check page

src/views/data-subject.html, src/views/dataset.html, src/views/email-address.html, src/views/lpa.html, src/views/name.html, src/views/upload.html
Ticket: https://trello.com/c/K5PsVVcT/1111-ensure-that-form-fields-remain-populated-between-page-navigations
this ticket just makes sure all the form fields are populated with the values stored in the session data
=> make sure form is populated with values in the session

.dockerignore, dockerfile
Ticket: https://trello.com/c/5pMmPK38/1113-dockerize-the-lpa-data-validator-frontend
this PR adds a dockerfile
=> started working on dockerizing the project

src/controllers/errorsController.js, src/controllers/uploadController.js, src/utils/utils.js, test/testData/API_RUN_PIPELINE_RESPONSE.json, test/unit/errorsController.test.js, test/unit/uploadController.test.js
Ticket: https://trello.com/c/femhyuvk/1114-make-use-of-the-severity-level-to-better-show-and-hide-errors
use the added severity field to only show issues with a severity of 'error'
=> Only show errors

src/controllers/datasetController.js, src/controllers/errorsController.js, src/routes/form-wizard/fields.js, src/routes/form-wizard/steps.js, src/utils/utils.js, src/views/confirmation.html, src/views/errors.html, src/views/start.html, test/acceptance/back_buttons.test.js, test/acceptance/pages_load_ok.test.js, test/acceptance/upload_data.test.js, test/acceptance/validation_errors.test.js, test/unit/errorsPage.test.js
This ticket realigns the implementation with the prototype https://publish-plan-mvp-mdsgfdw91wers.herokuapp.com/
=> Realign with prototype

index.js
=> Health check

dockerfile
Ticket: https://trello.com/c/zBqPcWcV/1118-onboard-the-lpa-data-validator-frontend-to-aws-dev
=> build scss after files have been copied

index.js, src/routes/form-wizard/steps.js
just a quick fix to make sure the first page correctly logs
=> make sure start page logs and also requests log IP and session

dockerfile
Ticket: https://trello.com/c/Qa0WRVxc/1115-improve-the-dockerfile-for-the-lpa-data-validator-to-be-a-multistage-build
this PR changes the docker image to be built using a multi stage build
it reduces the docker image size from 257mb to 82mb
=> update docker file to be multistage

index.js, src/routes/accessibility.js, src/views/accessibility.html, test/acceptance/pages_load_ok.test.js
Ticket: https://trello.com/c/OPo8jaaS/1127-mvp-accessibility-statement
this PR adds the accessibility page
=> Accessibility page

src/controllers/uploadController.js, src/filters/validationMessageLookup.js, src/routes/form-wizard/fields.js, src/views/upload.html
Ticket: https://trello.com/c/2jveMMis/1160-better-error-handling-for-the-upload-step
this ticket improves the error handling and display for a variety of api responses
=> Improve upload error handling

src/views/errors.html
Ticket: https://trello.com/c/v5JRhYVn/1177-ensure-safe-upload-of-files
this ticket just makes sure to sanitize the cell output from the uploaded data as code injection was possible
=> Sanitize output

src/views/errors.html, test/acceptance/upload_data.test.js, test/mock-api/index.js
This is a quick fix to a bug that causes the upload new version button not to work when you have uploaded using a URL
=> Upload new version bug

src/controllers/uploadFileController.js
Ticket: https://trello.com/c/pQqga1yS/1239-add-logging-for-file-size?filter=member:georgegoodall8
small change adding a log for the file sizes
=> File size logging

config/default.yaml, config/development.yaml, config/index.js, config/staging.yaml, config/test.yaml, package.json, readme.md, src/controllers/uploadController.js
Ticket: https://trello.com/c/W9QYm1Lv/1234-dynamically-select-api-url-based-on-runtime-environment?filter=member:georgegoodall8
This ticket ensures that the correct api is used depending on the ENVIRONMENT env variable
=> Dynamic api selection

src/controllers/pageController.js, src/controllers/uploadController.js, src/utils/logging.js
fix page logging by making get requests non async
=> Fix page view logging

src/utils/utils.js
this PR enables the new datasets
=> enable new datasets

docker/request-api-stub/wiremock/__files/check_file/article-4/request-complete-errors.json, docker/request-api-stub/wiremock/__files/check_file/article-4/request-complete.json, src/controllers/submitUrlController.js, src/controllers/uploadFileController.js, src/filters/validationMessageLookup.js, src/models/requestData.js, src/utils/asyncRequestApi.js, src/utils/getVerboseColumns.js, test/mock-api/index.js, test/unit/PageController.test.js, test/unit/publishRequestAPI.test.js, test/unit/validationLookup.test.js
Ticket: https://trello.com/c/5weYXp47/1359-reduce-502-and-503-errors?filter=label:Publish%20-%20Async,member:georgegoodall8
this work tries to make the codebase more robust to crashes.
=> Make codebase more robust against crashes

.gitignore, docker-compose.yml, docker/request-api-stub/README.md, docker/request-api-stub/wiremock/__files/check_file/article-4/request-complete.json, docker/request-api-stub/wiremock/__files/check_file/article-4/request-failed.json, docker/request-api-stub/wiremock/__files/check_file/article-4/request-new.json, docker/request-api-stub/wiremock/__files/request-created.json.handlebars, docker/request-api-stub/wiremock/mappings/check_file/article-4/get-request-complete.json, docker/request-api-stub/wiremock/mappings/check_file/article-4/get-request-failed.json, docker/request-api-stub/wiremock/mappings/check_file/article-4/get-request-new.json, docker/request-api-stub/wiremock/mappings/post-request.json
Added initial stubbing of async request-api using Wiremock and Docker Compose
=> Stubbing of async request-api

src/serverSetup/session.js
Backout of using secure cookie setting production for now since it requires some further investigation
=> Backout of using secure cookie setting in production

src/utils/utils.js
Ticket: https://trello.com/c/zqvLcAW3/1436-geopkg-not-processing
=> add octet steams to accepted file types

config/default.yaml, src/views/accessibility.html, src/views/start.html
Ticket: https://trello.com/c/JxJGSel3/3210-rename-publish-service-to-check-service?filter=member:georgegoodall8
this is a very short ticket that renames the publish service to the check service
=> update to check

src/models/requestData.js, src/models/responseDetails.js, test/unit/errorsPage.test.js, test/unit/noErrorsPage.test.js, test/unit/responseDetails.test.js
Ticket: https://trello.com/c/QXa3VJwh/3316-pagination-page-links-not-working
=> make sure id gets passed to the responseDetails class

package.json
=> add vite (missing dev dep)

src/views/submit/start.html
Ticket: https://trello.com/c/EWSamdIz/3373-esf-last-steps-before-we-put-to-bed
=> remove content

src/views/check/start.html
More consistent use of dataset names and file formats
https://trello.com/c/PFgJBb1d/3394-check-start-page-content-fixes
=> Fix start page content

.github/workflows/featureDeploy.yml
Ticket: https://github.com/orgs/digital-land/projects/7/views/9?pane=issue&itemId=72895628
=> added feature deploy workflow

src/assets/js/application.js, src/assets/js/js-hidden.js, src/assets/js/list-filter.js, src/assets/scss/index.scss, src/controllers/OrganisationsController.js, src/views/organisations/find.html, test/unit/findPage.test.js, webpack.config.mjs
Ticket: https://github.com/orgs/digital-land/projects/7/views/9?pane=issue&itemId=71541650
this ticket adds the basic nunjucks template for the find organisation page
currently, this is populated by static data, but we will be updating this to get the real data in a later PR
=> Feat/org finder/template

.gitignore, config/index.js, index.js, package-lock.json, package.json, src/assets/js/statusPage.js, src/controllers/uploadController.js, src/controllers/uploadFileController.js, src/serverSetup/errorHandlers.js, src/serverSetup/middlewares.js, src/serverSetup/session.js, src/services/asyncRequestApi.js, src/utils/getVerboseColumns.js, src/utils/logging.js, test/unit/PageController.test.js, test/unit/publishRequestAPI.test.js
- remove data repetition from 'info' objects
- use structured logging more consistently
- consistent use of 'type' property on info objects
There is a central location for log event 'types' in `src/utils/logging.js`. These should be pretty broad categories to avoid the proliferation of types. 
With this PR, [lnav](https://lnav.org/) and this [config](https://gist.github.com/rosado/2371524cf480d64ad219c3309b65e24a) (just put it in `~/.lnav/formats/installed/lpa_log.json`) you can view the logs in more civilised way:
=> Logging improvements

src/controllers/OrganisationsController.js, src/routes/organisations.js, src/views/organisations/datasetTaskList.html, test/unit/datasetTaskListPage.test.js, test/unit/organisationsController.test.js
Ticket: https://github.com/digital-land/lpa-data-validator-frontend/issues/223
this ticket adds basic routing and a controller for the dataset task list
=> Feat/dataset task list/router and controller

package-lock.json, package.json, src/controllers/OrganisationsController.js, src/routes/organisations.js, src/services/performanceDbApi.js, src/utils/issueMessages/getDatasetTaskList.js, src/utils/issueMessages/messages.csv, src/views/includes/_dataset-page-header.html, src/views/organisations/datasetTaskList.html, src/views/organisations/overview.html, test/unit/datasetTaskListPage.test.js, test/unit/organisationsController.test.js, test/unit/performanceDbApi.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/9?pane=issue&itemId=73538982
please review 229 before this PR
this ticket adds the template in for the dataset task list
=> Feat/dataset task list/template

src/controllers/OrganisationsController.js, src/filters/filters.js, src/routes/organisations.js, src/views/organisations/http-error.html, test/unit/http-errorPage.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/15?filterQuery=-status%3ABacklog%2CReady%2CDone%2CUnprioritised&pane=issue&itemId=73864558
this ticket adds a basic template for the endpoint error page
=> Feat/endpoint error/template

src/controllers/OrganisationsController.js, src/routes/organisations.js, src/services/performanceDbApi.js, test/unit/organisationsController.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/15?filterQuery=-status%3ABacklog%2CReady%2CDone%2CUnprioritised&pane=issue&itemId=74023064
this ticket updates the controller so it fetches live data and uses that to populate the tempalte
=> Feat/endpoint error/query

src/controllers/OrganisationsController.js, src/filters/filters.js, src/services/datasette.js, src/services/performanceDbApi.js, src/views/organisations/overview.html, test/unit/lpaOverviewPage.test.js, test/unit/organisationsController.test.js, test/unit/performanceDbApi.test.js
Issue: https://github.com/digital-land/lpa-data-validator-frontend/issues/252
This change includes a number of minor content updates and a bit more involved change around the 'status' of a dataset (how it is used in the code). 
content changes related to dataset 'status'
- arbitrary strings that were sometimes used, sometimes usedin combination with other columns, even when it looked like the same semantically we wanted the same information (e.g. `status`, which had values inconsistent with the ones we actually want to surface to the users, I can't find any reason why we would want them to be different)
- some post-processing of the data was done (e.g. adding `error` and `issue` columns in code) - I removed that and now the query returns the `error` column, the issue column was removed.
- …
=> Various content changes

src/views/organisations/datasetTaskList.html, src/views/organisations/issueDetails.html
Ticket: https://github.com/orgs/digital-land/projects/7/views/15?filterQuery=-status%3ABacklog%2CReady%2CDone%2CUnprioritised&pane=issue&itemId=74236695
this ticket just updates the href on one of the links to point to the check start page
=> make sure link points to check service

config/default.yaml, src/controllers/submitUrlController.js, src/controllers/uploadFileController.js, src/filters/validationMessageLookup.js, test/unit/submitUrlController.test.js, test/unit/uploadFileController.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/24?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%5D&pane=issue&itemId=75276876
this ticket increases the file size limit for urls and file uploads in the check service
=> increased file size restrictions

src/views/organisations/get-started.html
This page updates the step by step content on the get started page, so we dont link to the submit form:
=> update step by step content

src/controllers/uploadFileController.js, src/utils/utils.js
=> Add XML to supported mime types

readme.md
- Add in docker instructions
-  Add instructions for Mac users
- Docker is the recommended approach for running the application. This ensures that all the required services such as Request API, LocalStack etc. are running along with the application.
- For Mac users, port 5000 is used for AirPlay Receiver - these instructions help users run the application without refactoring the code.
=> Improve local development set up instructions

src/routes/form-wizard/check/steps.js, src/serverSetup/routes.js, src/views/check/start.html, src/views/organisations/datasetTaskList.html, src/views/organisations/get-started.html, src/views/organisations/issueDetails.html, test/PageObjectModels/confirmationPage.js, test/PageObjectModels/datasetPage.js, test/PageObjectModels/geometryTypePage.js, test/PageObjectModels/resultsPage.js, test/PageObjectModels/startPage.js, test/PageObjectModels/statusPage.js, test/PageObjectModels/submitURLPage.js, test/PageObjectModels/uploadFilePage.js, test/PageObjectModels/uploadMethodPage.js, test/integration/pages_load_ok.playwright.test.js
Ticket: https://github.com/orgs/digital-land/projects/7/views/24?filterQuery=assignee%3A%40me+-status%3ABacklog%2CUnprioritised%2C%22In+Testing%22%2C%22Ready+for+Dev%22%2C%22Scoping+for+Dev%22%2C%22Creating+Analysis%22%2C%22User+Research%2FTesting%22%2C%22In+design%22++sprint%3A%40current&pane=issue&itemId=74896459
this PR handles the first part of this ticket which is updating the subpaths for the site.
I'm not sure if we should merge this in before chris c and ernest return from holiday and can setup redirect links?
=> update check links

src/views/errorPages/400.html, test/unit/default-http-errors.test.js
Missing error page for 400 status code errors.
No ticket, but should be part of #340 originally
=> Add missing 400 error page

src/controllers/submitUrlController.js, test/unit/submitUrlController.test.js
Simplifies logic of testing accessibility of the user submitted URLs. 
Requires #344 to be merged first.
Fixes #300
=> Simplify  accessibility checks of submitted URLs

config/default.yaml, config/util.js, src/serverSetup/nunjucks.js, src/views/layouts/main.html, src/views/start.html, src/views/submit/start.html
Updated links and removed a section from the sidebar
Closes #358 
Closes #357 
=> Header and sidebar content fixes

src/views/organisations/get-started.html, test/unit/get-startedPage.test.js
'Get started' page: Content and design fixes
- Closes #356
To test go to a organisation's "Get started" page:
http://localhost:5000/organisations/government-organisation:PC163/article-4-direction/get-started
=> Get started page content and design fixes

src/controllers/OrganisationsController.js, src/models/responseDetails.js, src/routes/organisations.js, src/routes/schemas.js, src/services/performanceDbApi.js, src/utils/pagination.js, src/views/organisations/issueDetails.html, test/unit/issueDetailsPage.test.js, test/unit/organisationsController.test.js, test/unit/pagination.test.js, test/unit/responseDetails.test.js
- Feature
- Bug Fix
The primary purpose of this PR is to add the pagination to the bottom of the issue details page
It also updates the error summary heading on the issue details page to indicate the correct count of issues (as datasette limits returned rows to 1000, this was previously incorrect)
for now this has made another issue apparent which is the error summary component only shows 1k errors, this should be resolved in the future when the design is amended by Alex
- Ticket Link: https://github.com/orgs/digital-land/projects/7/views/24?filterQuery=assignee%3A%40me+-status%3ABacklog%2CUnprioritised%2C%22Ready+for+Dev%22%2C%22Scoping+for+Dev%22%2C%22Creating+Analysis%22%2C%22User+Research%2FTesting%22%2C%22In+design%22%2C%22Needs+Planning%22%2C%22In+Testing%22&pane=issue&itemId=7553498 …
=> Issue details/pagination

src/assets/scss/index.scss
Capitalise first word in the issue details header. Implemented via CSS.
Part of #355 
=> Capitalise heading in the issue details table

src/controllers/submitUrlController.js
Collect sentry metrics for user submitted URLs that we can't reach/access.
Related ticket: #373
=> Collect sentry metrics for url submission errors

package-lock.json, package.json, src/controllers/OrganisationsController.js, src/filters/filters.js, src/filters/pluralise.js, src/utils/utils.js, src/views/organisations/datasetTaskList.html, src/views/organisations/get-started.html, src/views/organisations/http-error.html, src/views/organisations/issueDetails.html, src/views/organisations/overview.html, test/unit/generic-page.js, test/unit/get-startedPage.test.js, test/unit/lpaOverviewPage.test.js
Fixes the following content issues:
- Org name in breadcrumb needs correct capitalisation
- Dataset list should be alphabetically ordered
- "Not submitted" tag should be grey
- "Live" tag shows alongside text showing issues exist / either the tag or the text is wrong
- When there's only a single issue the text should be "There is 1 issue in this dataset"
- Closes #354 
=> Organisation dashboard content and design fixes

src/views/check/results/errors.html, src/views/check/results/no-errors.html, test/unit/paginationTemplateTests.js
- Bug Fix
__*This is a hot fix, I will be opening another PR shortly to improve the quality and test coverage*__
This PR fixes the prev/next buttons on the results page pagination
=> fix prev/next links

src/content/entityIssueMessages.csv, src/content/fieldIssueMessages.csv, src/services/performanceDbApi.js, test/unit/performanceDbApi.test.js
- Bug Fix
added new messages for issue type 'entity-date'
updated getTaskMessage code to not throw an 'Unknown issue_type' error but instead log a warning and return a fallback message
- Closes #419 
- Yes: also further testing has been done in #386, but not yet merged in. will improve testing in #386 once this has been merged in
=> 419 bug broken links on north lincs overview page

.vscode/extensions.json, src/controllers/OrganisationsController.js, src/routes/organisations.js, src/routes/schemas.js, src/services/DatasetService.js, src/views/organisations/dataset-overview.html, src/views/organisations/overview.html, submit.code-workspace, test/unit/lpaOverviewPage.test.js, test/unit/services/DatasetService.test.js, test/unit/views/organisations/dataset-overview.test.js
Display overview page for live datasets without any issues.
Some things were changed from original spec - note made here: https://github.com/digital-land/submit/issues/311#issuecomment-2351799020
- Closes #387
<div>
<a href="https://www.loom.com/share/227d7999da294a23bb9b5e0facddb5a8">
<p>London Borough of Barnet overview - Submit and update your planning data - 16 September 2024 - Watch Video</p>
</a>
<a href="https://www.loom.com/share/227d7999da294a23bb9b5e0facddb5a8">
</a>
</div>
=> Visualise geospatial data on dataset details page

src/views/organisations/overview.html
Tree datasets are returning error as Datasette fails to return a result.
We are temporarily removing this view for these datasets while we investigate more performant solutions.
- Related Issue #387
=> Removes overview page for large datasets

src/views/start.html
Updates to the start page to better reflect new functionality of service.
Closes #391
=> Updates to start page content.

src/assets/js/map.js, src/controllers/OrganisationsController.js, src/routes/schemas.js, src/services/DatasetService.js, src/views/organisations/dataset-overview.html, src/views/organisations/overview.html, test/unit/services/DatasetService.test.js, test/unit/views/organisations/dataset-overview.test.js
- Adds GeoJSON URL support for maps
- Adds support for boundary GeoJSON URLs for maps
- Refactors map.js
- Shows map layers below labels
- Shows overview page for all datasets
- Closes #444
=> [#444] Implement GeoJSON layers on map view

config/index.js
Add port support to ensure PORT env variables are favoured rather than default value. This will allow us to set ports via environment variables.
- Closes #435
https://submit-pr-470.herokuapp.com/
=> Add port support to ensure PORT env variables are favoured rather than default value

src/controllers/submitUrlController.js, test/unit/submitUrlController.test.js
This change allows undefined `content-length` headers to be accepted.
We cannot rely on the content length header to always return or be accurate. Therefore, it's best this check is just a soft check and let the API enforce restrictions on uploaded dataset sizes.
- Closes #450 
=> Allow files with undefined `content-length` headers

test/unit/datasetTaskListPage.test.js, test/unit/findPage.test.js, test/unit/issueDetailsPage.test.js
Replaces plain nunjucks calls with our custom one, to ensure test data validation happens.
Minor update to test code in #489
=> Replace vanilla nunjucks calls with our custom one

src/middleware/datasetOverview.middleware.js
fix for recent breaking changes to performance db schema
=> update table name for performance database

src/middleware/datasetOverview.middleware.js, test/unit/middleware/datasetOverview.middleware.test.js
- Bug Fix
the performance database has just been updated, this PR updates our code so it interacts with the performance db in the correct way
- Closes #499 
Preview Link: https://submit-pr-504.herokuapp.com/organisations/local-authority:LBH/article-4-direction-area/overview
dataset details page working again
=> 499 fix bugs that arised from changes to the performance db

src/middleware/datasetOverview.middleware.js
The summary tables in the performance DB will be changed to include information endpoints that are not active. This PR adds a filter so that it excludes endpoints with an end date - ie nothing should change when the summary tables include extra information
https://trello.com/c/NJSZQBUZ/3512-perf-db-general-changes
=> adds endpoint end date filter to query (prep)

src/views/errorPages/400.html, src/views/errorPages/404.html
Fixes typo - changes `vou` to `you`
- Closes #518 
=> Fixes typo - changes `vou` to `you`

readme.md, src/views/accessibility.html, src/views/cookies.html, src/views/privacy-notice.html
Looks like I mistyped this URL the first time around, so I fixed it and also changed it to Submit.
=> Fix typo, change link

src/services/performanceDbApi.js
This was caused by a change made by infrastructure to the schema.
https://github.com/digital-land/digital-land-builder/pull/36
- Ticket Link
- Closes #
=> Fixes broken dashboards

src/middleware/datasetOverview.middleware.js
Gracefully handles missing mapping fields. There are some instances where mapping fields is missing.
- Ticket Link
- Closes #
=> Gracefully handles missing mapping fields

src/assets/js/map.js
- The map interface is missing controls to enable the user to interact with it.
- Users can move about the map using pinch-to-zoom controls on their trackpads, but they might not be aware of this, and might be using a mouse.
- We should add these controls in to the map interface.
- The controls need to be added in the JS set up: https://maplibre.org/maplibre-gl-js/docs/examples/navigation/
- Ticket Link
- Closes #443 
=> Add map controls

src/middleware/datasetOverview.middleware.js
Removes duplicate sources. Now brings back the latest resource back for the endpoint
- Ticket Link
- Closes #513
=> Removes duplicate sources

src/middleware/datasetOverview.middleware.js
It was assumed that resource end date would either have a valid value or be null but it seems like some values are empty strings.
This change adds the additional check which resolves this issue.
_Please replace this line with a brief description of the changes made._
- Ticket Link
- Related Issue #513 
- Closes #
=> Fixes missing endpoints due to missing empty string check

src/middleware/common.middleware.js, src/middleware/datasetOverview.middleware.js, src/middleware/datasetTaskList.middleware.js
Hot fix to make sure the http error page is shown
https://submit-pr-562.herokuapp.com/organisations/local-authority:GAT/listed-building-outline/overview
- No
=> make sure to show the http error page

package-lock.json, package.json
Older versions have the older crest therefore we need to update to the latest version - otherwise we would have to manage the crest image within the repo.
- Ticket Link
- Closes #
=> Bump GOVUK frontend to latest version to get new crest

src/views/organisations/dataset-overview.html
- Refactor
Increase pagination limit to 500.
This means less requests are made to the server as we will pull 500 geo location points at a time rather than 100.
- Ticket Link
- Closes #
=> Increase pagination limit to 500
